id: P008055
initial_creation_type: ocr
source_metadata:
  id: bdr:W23748
  title: བཀའ་གདམས་ཆོས་འབྱུང་གསལ་བའི་སྒྲོན་མེ
  author: ''
  volumes:
    fcbb7e1be38146338bbab6e07a5322ed:
      image_group_id: I2593
      title: ''
      volume_number: 1
      total_pages: 834
ebook_metadata:
  title: བཀའ་གདམས་ཆོས་འབྱུང་གསལ་བའི་སྒྲོན་མེ
  author: ''
  sku: P008055
  cover: cover.jpg
  layers:
  - pagination
