id: P008055
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:58:22.315842
source_metadata:
  id: bdr:W23748
  title: བཀའ་གདམས་ཆོས་འབྱུང་གསལ་བའི་སྒྲོན་མེ
  author: ''
  volumes:
    fcbb7e1be38146338bbab6e07a5322ed:
      image_group_id: I2593
      title: ''
      volume_number: 1
      total_pages: 834
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
